#!/usr/bin/env python3
"""
translate_charts.py — produce English-labelled copies of the SVG charts.

The charts are generated by build_charts.py with Chinese titles/footers.
This script replaces the (fixed, known) Chinese strings with English and
writes `*_en.svg` next to each chart, which the English notes reference.
No data refetch, no re-render — a pure text pass over the SVG.

Run:  python3 tools/translate_charts.py
"""
import glob
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHARTS = os.path.join(ROOT, "assets", "charts")

MAP = {
    # ---- titles ----
    "EIP-1559 月度 ETH 销毁量": "Monthly ETH Burned by EIP-1559",
    "累计销毁量（通缩型财政政策的规模）": "Cumulative Burn (the size of a deflationary fiscal policy)",
    "结构性税率 τ 的时间序列": "Structural Tax Rate τ over Time",
    "费用拆分：销毁 vs 验证者收入": "Fee Split: Burn vs Validator Income (tip)",
    "τ 与拥堵（平均 base fee）的关系": "τ vs Congestion (average base fee)",
    "区块 MEV 价值分布（proposer payload value）": "Distribution of Per-block MEV Value",
    "构建者集中度：Top-10 拿走的价值份额": "Builder Concentration: Value Share of Top-10",
    "MEV 价值 vs 区块 gas 使用量": "MEV Value vs Block Gas Used",
    "各 relay 的单区块平均 MEV 价值": "Average Per-block MEV by Relay",
    "收益率中有多少来自代币补贴？": "How Much Yield Comes from Token Subsidies?",
    "基础收益 vs 代币补贴（按 TVL 前 120 池）": "Base Yield vs Token Subsidy (top-120 pools by TVL)",
    "协议真实收入（30 天费用，百万美元）": "Real Protocol Revenue (30-day fees, USD m)",
    "补贴强度 vs TVL": "Subsidy Intensity vs TVL",
    "BTC 价格 vs 资金费率（7 日均值）": "BTC Price vs Funding Rate (7-day average)",
    "日度资金费率分布": "Daily Funding-Rate Distribution",
    "按资金费率分位：未来 7 日平均收益": "Forward 7-day Return by Funding Decile",
    "资金费率 vs 未来 7 日收益": "Funding Rate vs Forward 7-day Return",
    # ---- axis labels ----
    "平均 base fee (Gwei)": "Average base fee (Gwei)",
    # ---- footers ----
    "图 1-1 · 月度销毁量 · 数据: Blockchair aggregated API · 估算口径: avg(base_fee_per_gas) × Σ gas_used":
        "Fig 1-1 · Monthly burn · Source: Blockchair aggregated API · Estimate: avg(base_fee_per_gas) x Σ gas_used",
    "图 1-2 · 累计销毁量 · 数据: Blockchair · 估算口径同上":
        "Fig 1-2 · Cumulative burn · Source: Blockchair · Same estimate",
    "图 1-3 · τ = burn / (burn + tip) · 数据: Blockchair blocks + transactions":
        "Fig 1-3 · τ = burn / (burn + tip) · Source: Blockchair blocks + transactions",
    "图 1-4 · 费用分解 · 数据: Blockchair":
        "Fig 1-4 · Fee decomposition · Source: Blockchair",
    "图 1-5 · τ vs 平均 base fee · 数据: Blockchair · 每点 = 一个月":
        "Fig 1-5 · τ vs average base fee · Source: Blockchair · Each point = one month",
    "图 2-1 · 每区块 MEV 价值分布 · 数据: MEV-Boost relay 公开 bidtrace API · 样本 = 各 relay 最近 100 块":
        "Fig 2-1 · Per-block MEV value distribution · Source: MEV-Boost relay bidtrace API · Sample = latest 100 blocks per relay",
    "图 2-2 · 构建者价值份额 · 数据: relay bidtrace · 标签为 builder_pubkey 前 12 位":
        "Fig 2-2 · Builder value share · Source: relay bidtrace · Label = first 12 chars of builder_pubkey",
    "图 2-3 · MEV vs gas_used · 数据: relay bidtrace":
        "Fig 2-3 · MEV vs gas_used · Source: relay bidtrace",
    "图 2-4 · relay 对比 · 数据: 各 relay 公开 API · 每 relay 最近 100 块":
        "Fig 2-4 · Relay comparison · Source: each relay public API · Latest 100 blocks per relay",
    "图 3-1 · 补贴占比分布 · 数据: DefiLlama yields API · 样本 = TVL ≥ 1M USD 且含 base/reward APY 的池子":
        "Fig 3-1 · Subsidy-share distribution · Source: DefiLlama yields API · Sample = pools with TVL >= $1M and base/reward APY",
    "图 3-2 · base APY vs reward APY · 数据: DefiLlama  · 每点 = 一个池子":
        "Fig 3-2 · base APY vs reward APY · Source: DefiLlama · Each point = one pool",
    "图 3-3 · 协议 30 天费用 · 数据: DefiLlama fees API":
        "Fig 3-3 · Protocol 30-day fees · Source: DefiLlama fees API",
    "图 3-4 · TVL vs reward APY · 数据: DefiLlama yields · 每点 = 一个池子":
        "Fig 3-4 · TVL vs reward APY · Source: DefiLlama yields · Each point = one pool",
    "图 4-1 · 价格 vs 资金费率 · 数据: Hyperliquid BTC 永续 · 右轴 = 资金费率 7 日均值 (%)":
        "Fig 4-1 · Price vs funding · Source: Hyperliquid BTC perps · Right axis = 7-day average funding (%)",
    "图 4-2 · 资金费率分布 · 数据: Hyperliquid · 正值 = 多头付费给空头":
        "Fig 4-2 · Funding-rate distribution · Source: Hyperliquid · Positive = longs pay shorts",
    "图 4-3 · 资金费率十分位 vs 未来 7 日收益 · 数据: Hyperliquid":
        "Fig 4-3 · Funding decile vs forward 7-day return · Source: Hyperliquid",
    "图 4-4 · funding vs 未来 7 日收益 · 数据: Hyperliquid · 每点 = 一日":
        "Fig 4-4 · Funding vs forward 7-day return · Source: Hyperliquid · Each point = one day",
}


def main():
    files = [f for f in sorted(glob.glob(os.path.join(CHARTS, "*.svg")))
             if not f.endswith("_en.svg")]
    total = 0
    for f in files:
        with open(f, encoding="utf-8") as fh:
            src = fh.read()
        out = src
        for zh, en in MAP.items():
            out = out.replace(zh, en)
        dst = f[:-4] + "_en.svg"
        with open(dst, "w", encoding="utf-8") as fh:
            fh.write(out)
        total += 1
        print("  wrote", os.path.basename(dst))
    print(f"done: {total} English chart(s)")


if __name__ == "__main__":
    main()
